# -*- coding: utf-8 -*-
"""metodobisectriz.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rEMsOUz9jDiBkojJgEZ4doIn2P46INsa
"""

#AP
import numpy as np
import matplotlib.pyplot as plt
import time

def f(x):
    return np.sin(2*x+1)-3*x/5+1

x=np.linspace(-4,4)

print("x=\n",x)
print("f(x)=\n",f(x))
plt.plot(x,f(x))
plt.xlabel("x")
plt.ylabel("f(x)")
plt.grid(True)
plt.show()

a=-10
b=10
c=(a+b)/2
error=15
i=0


  
while error>1e-8:
  
  c=(a+b)/2
  fa=f(a)
  fc=f(c)
  if fc==0:
    raiz=c
    break
  
  elif fa*fc<0:
    b=c
  else:
    a=c
  raiz=c
  i+=1
  error=abs(fc)
start = time.time()
end = time.time()
timepo = end-start
 
  
  
print("La raiz de esta funcion es:",raiz)
print("Las iteraciones que realizo fueron:",i)
print("El tiempo que tardo el metodo de la bisección es:",end-start)




#METODO BUSQUEDA EXHAUSTIVA
start = time.time()
ini=-4
fin=4
c=0
xi=inicio
pas=0.0001

while inicio <=fin:
  dx=c*pas
  xi=ini-dx
  if f(x)<0.0001:
    break
  else:
    c=c+1

end = time.time()
elapsedNaive = end-start
print("El tiempo que tardo el metodo de busqueda exhaustiva es: ", (end-start))
print("Las raices de la funcion son:",xi)