# -*- coding: utf-8 -*-
"""método de las diferencias divididas de Newton.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vPYPES2p2mYOQ22RaeYSCwG8cY7GXwLI
"""

#ANDRE URIEL PEREDO NAVA
import numpy as np
import pandas as pd
import sympy as sym
import matplotlib.pyplot as plt


xi=np.array([15.992,15.091,15.117,14.771,11.849,10.92,10.087,9.958,8.981])
fi=np.array([462.11,475.11,533.47,652.65,660.76,658.26,676.23,729.37,722.3])

titulo=['i','xi','fi']
n=len(xi)
ki=np.arange(0,n,1)
tabla=np.concatenate(([ki],[xi],[fi]))
tabla=np.transpose(tabla)

dfinita=np.zeros(shape=(n,n),dtype=float)
tabla= np.concatenate((tabla,dfinita),axis=1)


[n,m]=np.shape(tabla)
diagonal=n-1
j=3
while(j<m):
  titulo.append('df'+str(j-2))
  paso=j-2
  i=0
  while(i<diagonal):
    numerador=tabla[i+1,j-1]-tabla[i,j-1]
    denominador=xi[i+paso]-xi[i]
    tabla[i,j]=numerador/denominador
    i=i+1
  diagonal=diagonal-1 
  j=j+1

h=xi[1]-xi[0]
dfinita=tabla[0,3:]
n=len(dfinita)
x=sym.Symbol('x')
polinomio=fi[0]

for j in range(1,n,1):
  factor=dfinita[j-1]
  termino=1
  for k in range(0,j,1):
    termino=termino*(x-xi[k])
  polinomio=polinomio+termino*factor

polisimple=polinomio.expand()


px=sym.lambdify(x,polisimple)

muestras=101
a=np.min(xi)
b=np.max(xi)
p_xi=np.linspace(a,b,muestras)
pfi=px(p_xi)



np.set_printoptions(precision=3)
print('Tabla Diferencia dividida')
print([titulo])
print(tabla)
print('Metodo de las diferencias divididas Newton:')
print(dfinita)
print('Polinomio:')
print(polinomio)
print('Polinomio simpplificado')
print(polisimple)


plt.plot(xi,fi,'o',label='Puntos')
plt.plot(p_xi,pfi,label='Polinomio')
plt.legend()
plt.xlabel('(xi)%Gastodesalud')
plt.ylabel('(fi)Gastototalmdd')
plt.title('Metodo de las diferencias divididas Newton:')
plt.show