# -*- coding: utf-8 -*-
"""ELIMINACION GAUSSIANA .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Sb4hiuHNLNfax-V5lQVYZAtpOTorh84a
"""

#ELIMINACION GAUSSIANA PAR INVERSA DE UNA MATRIZ
import numpy as np

def gaussElimin(a,b):
  n=len(b)


  #Eliminamos 

  for k in range(0,n-1):
    for i in range(k+1,n):
      if a[i,k] !=0.0:
        lam=a [i,k]/a[k,k]
        a[i,k+1:n]=a[i,k+1:n]-lam*a[k,k+1:n]
        b[i]= b[i]-lam*b[k]

  for k in range(n-1,-1,-1):
    b[k]=(b[k]-np.dot(a[k,k+1:n],b[k+1:n]))/a[k,k]
  return b 



#Escribimos las matrices 

A=np.array([[9.0,8.0,1.0],[-5.0,9.0,-1.0],[2.0,-9.0,4.0]])
b=np.array([15.0,-18.0,17.0])

gaussElimin(A,b)
Inv=np.linalg.inv(A)
print('\nNuestra matriz original es:',A)
print('\nLa inversa de la matriz es:',Inv)
print('La respuesta a nuestro sistema es:',b)